---
title: 'Westborough Mathcounts Announcements'
date: "11/2/2020"
output: pdf_document
---

## Registration fees

I've paid the Mathcounts organization for your registration. 

To reimburse me, please mail a check for $30 payable to Fred Boehm to:

Fred Boehm  
70 Pineland Ave  
Worcester, MA 01604

## Practice schedule

We'll practice once per week over zoom. I propose that we meet at 6:30 to 7:30pm every Monday.

## Homeworks

I'll assign "homework" practice exercises for you to complete between practice sessions. We'll dedicate part of each practice session to addressing questions from the homeworks.



## Mathcounts competition dates

https://www.mathcounts.org/sites/default/files/Critical%20Dates%202021_0.pdf

Feb 5, 2021: Chapter competition

Feb 25, 2021: Chapter invitational competition

Mar 25, 2021: State competition

May 8-11, 2021: National competition

## Additional participants

If you have friends who would like to participate in Mathcounts, please invite them to email Fred: frederick.boehm@gmail.com. All students (in grades 6, 7, and 8) are welcome!




